### ISSUE TITLE
Blizzard options category is "Raid Profiles" but not "Compact Raid Frames"

### ISSUE THREAD

**Issue by BannZay** [RomanSpector/CompactRaidFrame#10]
I think that blizzard addons category should match addon name, at least it is common thing for 3.3.5 addons.

**Comment by BannZay** [comment]
P.s.: https://github.com/RomanSpector/CompactRaidFrame/blob/f309dc60f2f00be7cca734e4818b7bc1a47d5998/CompactRaidFrame/CUFProfiles/CompactUnitFrameProfiles.lua#L12

**Comment by RomanSpector** [comment]
Not in this case, since it is in retail that "Raid Profiles" is displayed
