### ISSUE TITLE
Error: "TexCoord out of range" in function CompactUnitFrameUtil_UpdateFillBar

### ISSUE THREAD

**Issue by BannZay** [RomanSpector/CompactRaidFrame#12]
1x CompactRaidFrame-1.2.2\CompactUnitFrame.lua:859: TexCoord out of range
CompactRaidFrame-1.2.2\CompactUnitFrame.lua:859: in function `CompactUnitFrameUtil_UpdateFillBar'
CompactRaidFrame-1.2.2\CompactUnitFrame.lua:835: in function `CompactUnitFrame_UpdateHealPrediction'
CompactRaidFrame-1.2.2\CompactUnitFrame.lua:87: in function <...terface\AddOns\CompactRaidFrame\CompactUnitFrame.lua:49>

Locals:
frame = CompactRaidFrame1 {
 otherHealPrediction = CompactRaidFrame1OverlayTextureOtherHealPrediction {}
 debuffFrames = <table> {}
 ignoreParentAlpha = CompactRaidFrame1IgnoreAlphaTexture {}
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame1Background {}
 powerBar = CompactRaidFrame1PowerBar {}
 hasDispelPoison = false
 optionTable = <table> {}
 overAbsorbGlow = CompactRaidFrame1OverlayTextureOverAbsorbGlow {}
 horizTopBorder = CompactRaidFrame1HorizTopBorder {}
 vertRightBorder = CompactRaidFrame1VertRightBorder {}
 name = CompactRaidFrame1OverlayTextureName {}
 dropDown = CompactRaidFrame1DropDown {}
 inDistance = true
 myHealAbsorbRightShadow = CompactRaidFrame1OverlayTextureMyHealAbsorbRightShadow {}
 overHealAbsorbGlow = CompactRaidFrame1OverlayTextureOverHealAbsorbGlow {}
 newUnit = true
 overlay = CompactRaidFrame1OverlayTexture {}
 dispelDebuffFrames = <table> {}
 myHealAbsorbLeftShadow = CompactRaidFrame1OverlayTextureMyHealAbsorbLeftShadow {}
 totalAbsorbOverlay = CompactRaidFrame1OverlayTextureTotalAbsorbOverlay {}
 unit = "party1"
 unitExists = true
 healthBar = CompactRaidFrame1HealthBar {}
 updateAllEvent = "PARTY_MEMBERS_CHANGED"
 myHealPrediction = CompactRaidFrame1OverlayTextureMyHealPrediction {}
 aggroHighlight = CompactRaidFrame1OverlayTextureAggroHighlight {}
 statusText = CompactRaidFrame1OverlayTextureStatusText {}
 horizDivider = CompactRaidFrame1HorizDivider {}
 maxDebuffs = 3
 roleIcon = CompactRaidFrame1OverlayTextureRoleIcon {}
 totalAbsorb = CompactRaidFrame1OverlayTextureTotalAbsorb {}
 hasDispelCurse = false
 maxBuffs = 3
 centerStatusIcon = CompactRaidFrame1CenterStatusIcon {}
 buffFrames = <table> {}
 hasDispelMagic = false
 applyFunc = <function> @ CompactRaidFrame\CompactRaidFrames\CompactRaidFrameContainer.lua:341:
 myHealAbsorb = CompactRaidFrame1OverlayTextureMyHealAbsorb {}
 unusedFunc = <function> @ CompactRaidFrame\CompactRaidFrames\CompactRaidFrameContainer.lua:45:
 menu = <function> @ CompactRaidFrame\CompactUnitFrame.lua:255:
 vertLeftBorder = CompactRaidFrame1VertLeftBorder {}
 0 = <userdata>
 hasDispelDisease = false
 displayedUnit = "party1"
 horizBottomBorder = CompactRaidFrame1HorizBottomBorder {}
}
previousTexture = <unnamed> {
 0 = <userdata>
}
bar = CompactRaidFrame1OverlayTextureTotalAbsorb {
 0 = <userdata>
 overlay = CompactRaidFrame1OverlayTextureTotalAbsorbOverlay {}
}
amount = -3640
barOffsetXPercent = nil
totalWidth = 91.999985501905
totalHeight = 71.999972098006
barOffsetX = 0
_ = 0
totalMax = 1
barSize = -334879.94722694

  ---

**Comment by RomanSpector** [comment]
I have known about the error for a long time, but it is difficult to find what it is connected with.
Need help in debag.
Somehow the coordinates for TexCoord are calculated incorrectly and their value exceeds the permissible. I'm inclined that this is due to the LibHealComm-4.0 or AbsorbMonitor-1.0 library.
The error is not constant, so it is quite difficult to catch one what exactly the problem is.

**Comment by BannZay** [comment]
It does happens to me once per few days, Can I assist you with debugging?
I am not very familiar with code around but I could record a game or add logging to sus places.

**Comment by RomanSpector** [comment]
You need to replace the function and try to catch the error and send the result from the chat

```lua
function CompactUnitFrameUtil_UpdateFillBar(frame, previousTexture, bar, amount, barOffsetXPercent)
    local totalWidth, totalHeight = frame.healthBar:GetSize();

    if ( totalWidth == 0 or amount == 0 ) then
        bar:Hide();
        if ( bar.overlay ) then
            bar.overlay:Hide();
        end
        return previousTexture;
    end

    local barOffsetX = 0;
    if ( barOffsetXPercent ) then
        barOffsetX = totalWidth * barOffsetXPercent;
    end

    bar:SetPoint("TOPLEFT", previousTexture, "TOPRIGHT", barOffsetX, 0);
    bar:SetPoint("BOTTOMLEFT", previousTexture, "BOTTOMRIGHT", barOffsetX, 0);

    local _, totalMax = frame.healthBar:GetMinMaxValues();

    local barSize = (amount / totalMax) * totalWidth;
    bar:SetWidth(barSize);
    bar:Show();

    if  ( bar.overlay )
    and ( barSize     / bar.overlay.tileSize >  10001
    or    barSize     / bar.overlay.tileSize < -10001
    or    totalHeight / bar.overlay.tileSize >  10001
    or    totalHeight / bar.overlay.tileSize < -10001 ) then
        print("amount:", amount,
            "barOffsetXPercent:", barOffsetXPercent,
            "bar.overlay.tileSize:", bar.overlay.tileSize,
            "barSize:", barSize,
            "totalHeight:", totalHeight,
            debugstack())
        return bar;
    end

    if ( bar.overlay ) then
        bar.overlay:SetTexCoord(0, barSize / bar.overlay.tileSize, 0, totalHeight / bar.overlay.tileSize);
        bar.overlay:Show();
    end
    return bar;
end
```

**Comment by BannZay** [comment]
![изображение](https://user-images.githubusercontent.com/17499770/150653456-0d50909d-1fa3-4a97-a256-4c04743f8880.png)

**Comment by BannZay** [comment]
but I used [custom](https://github.com/BannZay/CompactRaidFrame/commit/5ec271c815014620a6a7067e27dcb07fa9adde8c) version (stacktrace could be affected cuse of this)
