### ISSUE TITLE
Clique Support

### ISSUE THREAD

**Issue by v3ceban** [RomanSpector/CompactRaidFrame#16]
For some reason this addon doesn't support clique :(

**Comment by RomanSpector** [comment]
https://discord.com/channels/750381752752668682/750381752752668685/850002052398055435

**Comment by mortza** [comment]
there is a issue with bot/role interaction message in your discord

**Comment by mortza** [comment]
can you post the snippet here ?

**Comment by RomanSpector** [comment]
Alright, some of you are using CompactRaidFrames and wanted to use Clique with them. Please don't modify Clique to work with it but rather modify CompactRaidFrames.

1. Open the file: CompactRaidFrame\CompactUnitFrame.lua
2. Scroll down and look for the function: CompactUnitFrame_SetUpFrame (line #207).
3. Add the followings lines at the end of the function:
ClickCastFrames = ClickCastFrames or {}
ClickCastFrames[frame] = true

This will register any frame created to the ClickCastFrames global table, thus adding them to Clique frames.
I hope this helps.

EDIT:
Please open locales.xml and make sure enUS.lua is first, then edit the file remove the check for GetLocale(), "enUS" should always be used by default.

**Comment by v3ceban** [comment]
Great, exactly what I needed! Thanks!
