### ISSUE TITLE
Interface action failed on openning settings while in combat

### ISSUE THREAD

**Issue by BannZay** [RomanSpector/CompactRaidFrame#22]
How to reproduce:
1. Enter combat
2. Open settings: Interface->Addons->Raid Profiles
3. Change any setting (Display pets for instance)
4. Check errors

![изображение](https://user-images.githubusercontent.com/17499770/149303739-64aa77a3-04cd-4e9c-b360-698a2c4e6ced.png)

One of erros trace:
_2x <event>ADDON_ACTION_BLOCKED:AddOn 'CompactRaidFrame' tried to call the protected function 'CompactRaidFrame1:SetPoint()'.
<in C code>: in function `SetPoint'
CompactRaidFrame-1.2.2\FlowContainer.lua:161: in function `FlowContainer_DoLayout'
CompactRaidFrame-1.2.2\FlowContainer.lua:17: in function `FlowContainer_ResumeUpdates'
...rame\CompactRaidFrames\CompactRaidFrameContainer.lua:192: in function `CompactRaidFrameContainer_LayoutFrames':
...rame\CompactRaidFrames\CompactRaidFrameContainer.lua:137: in function `CompactRaidFrameContainer_TryUpdate':
...ctRaidFrame\CUFProfiles\CompactUnitFrameProfiles.lua:577: in function `CompactUnitFrameProfiles_ApplyProfile':
...ctRaidFrame\CUFProfiles\CompactUnitFrameProfiles.lua:177: in function `CompactUnitFrameProfiles_ApplyCurrentSettings':
...ctRaidFrame\CUFProfiles\CompactUnitFrameProfiles.lua:548: in function `CompactUnitFrameProfilesCheckButton_OnClick':
<string>:"*:OnClick":1: in function <[string "*:OnClick"]:1>_

The left panel wont show itself up in combat, but interface options are not disabled.

**Comment by BannZay** [comment]
It is just an Addon_action_blocked but still a bug. Just to let you know

**Comment by RomanSpector** [comment]
A common error due to the state of the battle, nothing terrible for ordinary users
