### ISSUE TITLE
bug heal incoming is out of the cell

### ISSUE THREAD

**Issue by abel8909** [RomanSpector/CompactRaidFrame#5]
I did the test by disabling all the addons, as you can see video the heal incoming is out of the cell when hp is at 100%

https://user-images.githubusercontent.com/89325544/132876752-7e33ab5c-cc75-476e-a459-808e8c3e2e5e.mp4

**Comment by RomanSpector** [comment]
This is a blizzlike. You can see it in any movie from retail

**Comment by abel8909** [comment]
> This is a blizzlike. You can see it in any movie from retail

What? I did not understand? this has no solution?
the video I send, you can see that the cell box, after 100% hp, the texture of heal incoming is out of the cell box

**Comment by RomanSpector** [comment]
0:45
https://youtu.be/LS1zBHT9zBw?t=47
