### ISSUE TITLE
Lots of taint errors in party

### ISSUE THREAD

**Issue by jonomurphy** [RomanSpector/CompactRaidFrame#9]
Have noticed a lot of taint errors appearing with CompactRaidFrame when in dungeons. No other addons activated.

**Comment by RomanSpector** [comment]
at least a screenshot of the errors would not hurt

**Comment by jonomurphy** [comment]
Apologies - i thought i attached:

1x LibHealComm-4.0-66:1629: Usage: UnitGUID("unit")
LibHealComm-4.0-66:1629: in function `?'
LibHealComm-4.0-66:2745: in function <...ctRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2744>

Locals:
self = <table> {
 TargetLastTarget = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2454:
 GetHealModifier = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:360:
 bucketFrame = <unnamed> {}
 TargetLastFriend = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2450:
 compressGUID = <table> {}
 UNIT_SPELLCAST_CHANNEL_START = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2307:
 GetNextHealAmount = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:383:
 ALL_HEALS = 23
 GLYPH_ADDED = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1703:
 fixedAverage = true
 averageHeal = <table> {}
 UseAction = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2459:
 itemSetsData = <table> {}
 currentModifiers = <table> {}
 aurasUpdated = true
 GLYPH_REMOVED = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1703:
 GetCasterHealAmount = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:507:
 fixedCompress = true
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2369:
 BOMB_HEALS = 16
 callbacks = <table> {}
 GLYPH_UPDATED = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1703:
 removeRecordList = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:261:
 getRecord = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:224:
 GlyphsUpdated = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1703:
 Target = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2413:
 GetOthersHealAmount = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:496:
 UNIT_AURA = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1628:
 tableCache = <table> {}
 GetPlayerHealingMod = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:355:
 UPDATE_MOUSEOVER_UNIT = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2391:
 ZONE_CHANGED_NEW_AREA = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1607:
 healingModifiers = <table> {}
 hotMonitor = <unnamed> {}
 spellData = <table> {}
 guidToUnit = <table> {}
 CastSpell = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2459:
 DeleteTable = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:110:
 averageHealMT = <table> {}
 TargetUnit = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2413:
 OnInitialize = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2658:
 PLAYER_ENTERING_WORLD = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:1602:
 equippedSetCache = <table> {}
 rankNumbers = <table> {}
 talentData = <table> {}
 activePets = <table> {}
 UNIT_PET = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2563:
 RAID_ROSTER_UPDATE = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2620:
 unitToPet = <table> {}
 CastSpellByID = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2459:
 CHANNEL_HEALS = 2
 PLAYER_LOGIN = <function> @ CompactRaidFrame\Libs\LibHealComm-4.0\LibHealComm-4.0.lua:2757:
 eventFrame = <unnamed> {}
 CHA
  ---

**Comment by RomanSpector** [comment]
Oh, it's the famous UNIT_AURA event that fires without arguments. This is a server error that happens once a year:) there is no desire to sculpt a crutch for this
